### ISSUE TITLE
HAIRUN

### ISSUE THREAD

**Issue by ApellesNjenga** [Trans-DevLan/eReservations#2]
![Screenshot (7)](https://user-images.githubusercontent.com/97639933/194107372-df2bcae3-5e85-45fc-8bb1-de4b3b02ab8e.png)

**Comment by MartMbithi** [comment]
Do not rename the main application folder name. It will break the application

**Comment by ApellesNjenga** [comment]
[image: Screenshot (15).png]
the issue remaining is the popup for mpesa, haitokei
